export const restArray = [
  {
    id: 0,
    title: 'Пицца Плюс',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'pizzaPluse.jpg',
  },
  {
    id: 1,
    title: 'Тануки',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'tanuki.jpg',
  },
  {
    id: 2,
    title: 'FoodBand',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'foodBand.jpg',
  },
  {
    id: 3,
    title: 'Жадина-пицца',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'jadinaPizza.jpg',
  },
  {
    id: 4,
    title: 'Точка еды',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'pointOfFood.jpg',
  },
  {
    id: 5,
    title: 'PizzaBurger',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'PizzaBurger.jpg',
  },
]
